export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const AMEND_PRODUCT = 'AMEND_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const TAB_CLICK = 'TAB_CLICK';
